# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
##### Common Providers #####

terraform {
  required_version = "1.3.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.10"
    }
  }
}

provider "aws" {
  profile = var.profile
  region  = var.region
  default_tags {
    tags = {
      domain_name = var.domain_name
      service     = var.service
      namespace   = var.namespace
      environment = terraform.workspace
      location    = "infra/www/pbrand"
    }
  }
}

##### Common variables ######
variable "region" {
  description = "default region associated with this account"
  type        = string
  default     = "eu-central-1"
}
variable "profile" {
  type    = string
  default = "bymv-dev"
}
variable "tf_bucket_name" {
  type    = string
  default = "tf-infrastructure-management"
}
variable "tf_dynamodb_table" {
  type    = string
  default = "tf-infrastructure-management-table"
}
