# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

terraform {
  backend "s3" {
    bucket         = "tf-infrastructure-management"
    key            = "infra/www/pbrand/terraform.tfstate"
    region         = "eu-central-1"
    dynamodb_table = "tf-infrastructure-management-table"
    profile        = "bymv-dev"
  }
}
