# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "service" {
  description = "type of service"
  type        = string
}

variable "name" {
  description = "Main name of the resources"
  type        = string
}

variable "domain_name" {
  description = "Main domain where this resources belongs to"
  type        = string
}
variable "namespace" {
  description = "Web name"
  type        = string
}
variable "cnmanage_key" {
  description = "Certification tfstate key"
  type        = string
}
variable "aliases" {
  description = "Alises used for the web page"
  type        = list(string)
}
variable "acm_certification" {
  description = "ACM Certification ARN"
  type        = string
}
variable "route_53_zone_id" {
  description = "Route 53 Zone ID"
  type        = string
}